name: migrate-room

on:
  workflow_dispatch:

  push:
    branches: 
      - main
      - end
    paths:
      - 'migrate-room/**'
      - '.github/workflows/migrate-room.yml'
  pull_request:
    paths:
      - 'migrate-room/**'
      - '.github/workflows/migrate-room.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Unique group for each branch/workflow
  cancel-in-progress: true # Cancel previous jobs when a new commit is pushed

env:
  SAMPLE_PATH: migrate-room
  GRADLE_ENCRYPTION_KEY: CEehTVQluq6Ci3k7XSPctw==

jobs:
  androidBuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.SAMPLE_PATH }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ env.GRADLE_ENCRYPTION_KEY }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Spotless check
        run: ./gradlew spotlessCheck --stacktrace

      - name: Build project
        run: ./gradlew assembleDebug lintDebug --stacktrace

  iosBuild:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run xcodebuild
        uses: mxcl/xcodebuild@v3
        with:
          xcode: ^16
          scheme: Fruitties
          platform: iOS
          action: build
          working-directory: ${{ env.SAMPLE_PATH }}/iosApp   
